routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/zabbixreport', function (){
   return view('welcome');
})-> name('zabbixreport');

Route::get('/date?grid=Dates&advanced-search=true')-> name('search');

Route::get('/groups', 'ZabbixGroupController@index')->name('groups');

Route::get('/hosts/{group_id}', 'ZabbixHostController@index')->name('hosts');

Route::get('/items/{host_id}', 'ZabbixItemsController@index')->name('items');

Route::get('item/{item_id}', 'ZabbixItemsController@showForm')->name('form_item');
Route::post('proccessItem', 'ZabbixItemsController@item')->name('item');
Route::get('download/{filename}', 'ZabbixItemsController@download')->name('download');

Route::get('history/{item_id}', 'ZabbixItemsController@history')->name('history');

Route::get('test', 'ZabbixItemsController@test')->name('test');


/**
 * DATAS
 */

Route::get('/ajax-host', 'ZabbixHostController@list')->name('pathHost');

Route::resource('date', 'DateController');

app/Models/Date.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon; 

class Date extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'dates_holidays';
    
    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;
    
    public function setDatDayAttribute($value)
    {
        // 29/04/1988 => 1988-04-29
        $this->attributes['dat_day'] = Carbon::createFromFormat('d/m/Y', $value)->format('Y-m-d'); 
    }
    
    public function getDatDayAttribute($value)
    {
        // 1988-04-29 => 29/04/1988
        return Carbon::createFromFormat('Y-m-d', $value)->format('d/m/Y'); 
    }
}

app/Http/Controllers/DateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\DateRepository;
use App\Services\ZabbixGroupService;
use App\Http\Requests\DateRequest;
use Rafwell\Simplegrid\Grid;
use App\Models\Date;

class DateController extends Controller {

    protected $data = [];
    private $repository;
    private $zabbixService;

    public function __construct(DateRepository $repository, ZabbixGroupService $zabbixService) {
        $this->repository = $repository;
        $this->zabbixService = $zabbixService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        return $this->list();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $this->data['groups'] = $this->zabbixService->getGroups();
        return view('dates.create')->with($this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DateRequest $request) {
        if ($request->isMethod('post')) {

            if ($this->repository->isAvailable($request->date, $request->host)) {
                $date = $this->repository->create($request);
                
                 $msg = 'Gravado com sucesso!';
                return redirect()->route('date.create')
                                ->with('msg', $msg)
                                ->withInput();
            } else {
                $msg = 'Essa data já foi cadastrada para este host!';
                return redirect()->route('date.create')
                                ->with('msg', $msg)
                                ->withInput();
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {

        $date = $this->repository->findById($id);

        $this->data['groups'] = $this->zabbixService->getGroups();
        $this->data['hosts'] = array_map(function($day) {
            $tmp = new \stdClass();
            $tmp->id = $day->hostid;
            $tmp->hostname = $day->host;
            return $tmp;
        }, $this->zabbixService->getHosts($date->dat_group));


        $this->data['date'] = $date;
        return view('dates.edit')->with($this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {

        $date = $this->repository->findById($id);
        if ($request->date !== $date->dat_day) {
            if ($this->repository->isAvailable($request->date, $request->host)) {
                $this->repository->update($id, $request);

                $msg = 'Atualizado com sucesso!';
                return redirect()->route('date.edit', ['id' => $id])
                                ->with('msg', $msg)
                                ->withInput();
            } else {
                $msg = 'Essa data já foi cadastrada para este host!';
                return redirect()->route('date.edit', ['id' => $id])
                                ->with('msg', $msg)
                                ->withInput();
            }
        } else {
            $this->repository->update($id, $request);
             $msg = 'Atualizado com sucesso!';
             return redirect()->route('date.edit', ['id' => $id])
                             ->with('msg', $msg)
                             ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $this->repository->destroy($id);
        return redirect()->route('date.index');
    }

    public function list() {
        $Grid = new Grid(Date::query(), 'Dates');

        $Grid->fields([
                    'dat_day' => 'Data',
                    'dat_host' => 'ID. Host',
                    'dat_host_name' => 'Hostname',
                    'dat_comment' => 'Comentário',
                ])
                ->actionFields([
                    'id' //The fields used for process actions. those not are showed 
                ])
                ->advancedSearch([
                    'dat_day' => [
                        'type' => 'text',
                        'label' => 'Data'
                    ],
                    'dat_host' => [
                        'type' => 'text',
                        'label' => 'ID. Host'
                    ]
        ]);

        $Grid->action('Editar', 'date/{id}/edit')
                ->action('Deletar', 'date/{id}', [
                    'confirm' => 'Essa é uma ação irreversível. Deseja continuar? ',
                    'method' => 'DELETE',
        ]);

        return view('dates.list', ['grid' => $Grid]);
    }

}

resources/views/dates/create.blade.php
@extends('template')
@section('title', 'Criação de data')

@section('content')
<div class="container">

    <div class="row">
        <div class="col-xl-12">
            
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @if(session('msg'))
                <div class="alert alert-danger">
                    {{session('msg')}}
                </div>
            @endif

            <div class="row">
                <div class="col-xl-12 text-right">
                    <a href="{{route('search')}}" class="btn-link">Listar todos</a>
                </div>
            </div>
            
            <form action="{{route('date.store')}}" method="POST">
                {{ csrf_field() }}

                <div class="form-row">
                    <div class="col">
                        <div class="form-group">
                            <label for="date"> * Data </label>
                            <input type="text" 
                                name="date" 
                                id="datepicker" 
                                class="form-control br-date" 
                                placeholder="dd/mm/yyyy"
                                required
                                value="{{old('date')}}"
                            >
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="group"> * Group </label>
                            <select name="group" class="form-control" required id="group">
                                <option value="">--</option>
                                @if(count($groups) > 0 )
                                    @foreach($groups as $group)
                                        <option value="{{$group->groupid}}">{{$group->groupid}} - {{$group->name}}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="host"> * Host </label>
                            <select name="host" class="form-control" required id="host">
                                <option value="">--</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <div class="form-group">
                            <label for="comment" class="d-block">Comentário</label>
                            <textarea name="comment" id="comment" class="form-control" cols="30" rows="10">{{old('comment')}}</textarea>
                        </div>
                    </div>
                </div>
                
                <div class="form-row">
                    <div class="col">
                        <div class="form-group">
                            <input type="submit" value="Gravar" class="btn btn-primary active" role="button" aria-pressed="true">
                            <input type="hidden" id="pathLoadHost" value="{{route('pathHost')}}">
                            <a href="{{route('zabbixreport')}}" class="btn btn-secondary active" role="button" aria-pressed="true">Voltar</a>                            
                        </div>               
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
@endsection

resources/views/dates/edit.blade.php
@extends('template')
@section('title', 'Criação de data')

@section('content')
<div class="container">

    <div class="row">
        <div class="col-xl-12">
            
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @if(session('msg'))
                <div class="alert alert-danger">
                    {{session('msg')}}
                </div>
            @endif

            <div class="row">
                <div class="col-xl-12 text-right">
                    <a href="{{route('date.index')}}" class="btn-link">Listar todos</a>
                    <a href="{{route('date.create')}}" class="btn-link">Criar nova</a>
                </div>
            </div>
            
            <form action="{{route('date.update', ['id' => $date->id])}}" method="post">
                {{ csrf_field() }}
                @method('PUT')
                
                <div class="form-row">
                    <div class="col">
                        <div class="form-group">
                            <label for="date"> * Data </label>
                            <input type="text" 
                                name="date" 
                                id="datepicker" 
                                class="form-control br-date" 
                                placeholder="dd/mm/yyyy"
                                required
                                value="{{$date->dat_day}}"
                            >
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="group"> * Group </label>
                            <select name="group" class="form-control" required id="group">
                                <option value="">--</option>
                                @if(count($groups) > 0 )
                                    @foreach($groups as $group)
                                        @if($date->dat_group == $group->groupid)
                                            <option value="{{$group->groupid}}" selected>{{$group->groupid}} - {{$group->name}}</option>
                                        @else
                                            <option value="{{$group->groupid}}">{{$group->groupid}} - {{$group->name}}</option>
                                        @endif
                                    @endforeach
                                @endif
                            </select>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="host"> * Host </label>
                            <select name="host" class="form-control" required id="host">
                                <option value="">--</option>
                                @if(count($hosts) > 0 )
                                    @foreach($hosts as $host)
                                        @if($date->dat_host == $host->id)
                                            <option value="{{$host->id}} - {{$host->hostname}}" selected>{{$host->id}} - {{$host->hostname}}</option>
                                        @else
                                            <option value="{{$host->id}} - {{$host->hostname}}">{{$host->id}} - {{$host->hostname}}</option>
                                        @endif
                                    @endforeach
                                @endif
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <div class="form-group">
                            <label for="comment" class="d-block">Comentário</label>
                            <textarea name="comment" id="comment" class="form-control" cols="30" rows="10">{{$date->dat_comment}}</textarea>
                        </div>
                    </div>
                </div>
                
                <div class="form-row">
                    <div class="col">
                        <div class="form-group">
                            <input type="submit" value="Gravar" class="btn btn-primary">
                            <input type="hidden" id="pathLoadHost" value="{{route('pathHost')}}">
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
@endsection

resources/views/dates/list.blade.php
@extends('template')
@section('title', 'Listagem de datas')

@section('content')
<div class="container">

    <div class="row">
        <div class="col-xl-12 text-right">
            <a href="{{route('zabbixreport')}}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Nova Data</a>                            
            <a href="{{route('zabbixreport')}}" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Página Inicial</a>                            
            
        </div>
        <div class="col-xl-12">
            <div class="alert alert-warning">
                Na busca avançada, usar a data no formato US : Ano-mes-dia Ex.: 2020-12-20
            </div> <br>
            
            {!!$grid->make()!!}
        </div>
    </div>
</div>
@endsection